name: Build Windows Manual

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        cfg:
          - { os: windows-latest, python-version: '3.11', architecture: x64 }

    runs-on: ${{ matrix.cfg.os }}
    defaults:
      run:
        shell: bash

    steps:
    - name: Clone
      uses: actions/checkout@v6

    - name: Set up Python ${{ matrix.cfg.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.cfg.python-version }}
        architecture: ${{ matrix.cfg.architecture }}

    - name: Install dependencies
      run: |
        pip install build

    - name: Build Wheels
      shell: pwsh
      run: |
        $env:BDISTWHEELFREEZELIBS = "true"
        python -m build

    - name: Upload Compiled Wheel
      uses: actions/upload-artifact@v6
      with:
        name: Amulet-Compiled-Wheel
        path: dist/*.whl
